spacing = 1
padding = 1
hide_ascii = false
hide_bar_delimiters = false
prefer_small_ascii = false
separator = ""
palette = "None"

[bar]
glyph = "ߋ"
symbol_open = '['
symbol_close = ']'
visible = false

[box]
title = "┤ This is the sound of the future ├"
visible = true

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
color = "White"
path = "~/.config/macchina/ascii/elephant.txt"

[randomize]
key_color = false
separator_color = false

[keys]
host       = "      Host"
kernel     = "    Kernel"
battery    = "   Battery"
os         = "        OS"
de         = "        DE"
wm         = "        WM"
distro     = "    Distro"
terminal   = "  Terminal"
shell      = "     Shell"
packages   = "  Packages"
uptime     = "    Uptime"
memory     = "    Memory"
machine    = "   Machine"
local_ip   = "  Local IP"
backlight  = "Brightness"
resolution = "Resolution"
cpu_load   = "  CPU Load"
cpu        = "       CPU"
