repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
      - name: Remove trailing whitespace
        id: trailing-whitespace
      - name: Check for files that would have a conflict on case-insensitive filesystem
        id: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
      - name: Don't allow adding large files
        id: check-added-large-files

  # Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Validate Python
        id: check-ast

  # YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Validate YAML
        id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - name: Format YAML files
        id: prettier
        types: [yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Sort YAML files
        id: sort-simple-yaml

  # JSON
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Validate JSON
        id: check-json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - name: Format JSON files
        id: prettier
        types: [json]

  # TOML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Validate TOML
        id: check-toml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - name: Format TOML files
        id: prettier
        types: [toml]

  # Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - name: Format markdown files
        id: prettier
        types: [markdown]

  # Other files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - name: Format other files
        id: prettier
        exclude_types: [yaml, json, toml, markdown]
