repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
      - name: Remove trailing whitespace
        id: trailing-whitespace
      - name: Check for files that would have a conflict on case-insensitive filesystem
        id: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
      - name: Don't allow adding large files
        id: check-added-large-files
