#!/usr/bin/env just --justfile

guix_profiles_folder := env_var("XDG_CONFIG_HOME") / "guix-profiles"
packages_file := guix_profiles_folder / "packages.json"
manifest_file := guix_profiles_folder / "manifest.scm"
default_profile_folder := guix_profiles_folder / "default"

default: sort generate apply

sort:
    sort-json {{packages_file}} | jq . | sponge {{packages_file}}

generate:
    generate-guix-manifest --packages-file={{packages_file}} --manifest-file={{manifest_file}}

apply:
    guix package --manifest={{manifest_file}} --profile={{default_profile_folder}}
