assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["containers", "github_cli_extensions", "node", "pip3", "snap"]
skip_notify = true

[git]
repos = ["~/.dotfiles"]
pull_predefined = false
