[misc]
assume_yes = true
disable = [
    "containers",
    "distrobox",
    "flutter",
    "github_cli_extensions",
    "guix",
    "node",
    "pip3",
    "snap",
]

[commands]
"Guix" = "fish $XDG_CONFIG_HOME/guix/upgrade-guix.fish"
"Nix garbage collection" = "nix-collect-garbage --delete-old"
"Ubunix" = "cd $XDG_CONFIG_HOME/ubunix && just"
